version: "3"
services:
  # Serviço do seu projeto
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444"]
      interval: 30s
      timeout: 10s
      retries: 10
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - SELENIUM_URL=http://selenium:4444
    env_file:
    - ./src/.env
    # coloque o número do processo
    command: python -m pipenv run python src/main.py -p 12345


networks:
  default:
    driver: bridge
